- src/commands/upgrade.ts
Few adjustement to the upgrade command after release
> fix: upgrade version check

- src/commands/auth.ts
- src/commands/help.ts
- src/commands/upgrade.ts
- src/commands/use.ts
- src/commands/version.ts
- src/commands/whoami.ts
- src/index.ts
- src/utils/auth.config.utils.ts
- src/utils/satellite.utils.ts
> feat: profiles

- esbuild.mjs
- package-lock.json
- package.json
- src/utils/open.utils.ts
Solve thanks to https://github.com/sindresorhus/open/issues/302#event-8792339296
> build: bump open v9.0.0 with esm

- src/commands/help.ts
- src/commands/upgrade.ts
- src/commands/version.ts
- src/utils/github.utils.ts
> feat: check CLI version

- src/commands/upgrade.ts
> feat: filter upgrade

- src/commands/deploy.ts
> fix: encode full path

- src/commands/auth.ts
- src/utils/actor.utils.ts
- src/utils/process.utils.ts
> feat: support for JUNO_TOKEN process env

- package-lock.json
- package.json
- src/commands/deploy.ts
- src/commands/links.ts
- src/commands/open.ts
- src/commands/whoami.ts
- src/index.ts
- src/utils/domain.utils.ts
> feat: print links after deploy and whoami

- templates/failure.html
- templates/success.html
Bare minimum style.
Resolves #33
> feat: style login html page

- package-lock.json
- package.json
- src/commands/config.ts
- src/commands/upgrade.ts
- src/utils/wasm.utils.ts
Relates to https://github.com/buildwithjuno/juno/issues/167
> feat: support for storage rewrites config

- src/commands/deploy.ts
> feat: catch error when source folder no correctly defined

- src/commands/deploy.ts
- src/utils/deploy.utils.ts
> feat: skip empty files per default on deploy

- src/commands/deploy.ts
- src/constants/constants.ts
- src/constants/deploy.constants.ts
- src/types/satellite.config.ts
- src/utils/compress.utils.ts
> feat: compress

- src/commands/init.ts
- src/commands/version.ts
- src/configs/juno.config.ts
- src/types/juno.config.ts
This will be useful for the new vite plugin
https://github.com/junobuild/plugins
> feat: propagate orbiter id to juno.json

- src/commands/clear.ts
- src/commands/deploy.ts
- src/commands/help.ts
- src/index.ts
- src/services/clear.services.ts
- src/utils/msg.utils.ts
> feat: --clear option for deploy

- package-lock.json
- package.json
- src/commands/upgrade.ts
- src/services/upgrade.services.ts
> feat: redo custom domains after upgrade reset

- src/services/deploy.services.ts
- src/types/juno.config.ts
> feat: heap memory option

- src/commands/clear.ts
- src/commands/help.ts
- src/index.ts
- src/services/clear.services.ts
> feat: clear a particular file (fullPath)

- src/constants/constants.ts
> feat: use non raw domain and custom domain name for the cdn

- src/commands/help.ts
- src/commands/upgrade.ts
- src/services/upgrade.services.ts
- src/types/upgrade.ts
> feat: option to skip assert on upgrade

- src/commands/help.ts
- src/commands/upgrade.ts
> feat: replace subcommand upgrade to target

- src/services/clear.services.ts
Temporary workaround related to https://github.com/junobuild/juno/issues/484
> feat: list and set domains for juno clear

- src/commands/auth.ts
- src/commands/config.ts
- src/commands/deploy.ts
- src/commands/init.ts
- src/commands/open.ts
- src/commands/use.ts
- src/commands/version.ts
- src/commands/whoami.ts
- src/configs/cli.config.ts
- src/configs/cli.settings.config.ts
- src/constants/constants.ts
- src/index.ts
- src/services/clear.services.ts
- src/services/cli.settings.services.ts
- src/services/controllers.services.ts
- src/services/deploy.services.ts
- src/services/links.services.ts
- src/services/login.services.ts
- src/services/upgrade/upgrade.mission-control.services.ts
- src/services/upgrade/upgrade.orbiter.services.ts
- src/services/upgrade/upgrade.satellite.services.ts
- src/stores/settings.store.ts
- src/types/cli.config.ts
- src/utils/actor.utils.ts
- src/utils/config.utils.ts
- src/utils/satellite.utils.ts
> feat: optional encode config

- package-lock.json
- package.json
- src/commands/config.ts
Relates to https://github.com/junobuild/juno/issues/665
> feat: storage and datastore config for max memory size

- src/commands/help.ts
- src/services/links.services.ts
- src/stores/settings.store.ts
- src/utils/process.utils.ts
Useful to run `juno dev start` in CI
> feat: add option headless

- package-lock.json
- package.json
- src/commands/deploy.ts
> feat: pre- and postdeploy

- templates/docker/docker-compose.yml
> feat: add port 5999 to docker compose

- src/api/ic.api.ts
- src/commands/backup.ts
- src/help/backup.help.ts
- src/help/target.help.ts
- src/help/upgrade.help.ts
- src/index.ts
- src/services/backup/backup.mission-control.services.ts
- src/services/backup/backup.orbiter.services.ts
- src/services/backup/backup.satellite.services.ts
- src/services/backup/backup.services.ts
juno backup create
juno backup restore
juno backup delete
> feat: backup commands

- src/services/build.services.ts
Useful for `juno dev build`.
// Depending on the `tsconfig`, the `factory.did.js` file might be validated.
// Cleaning the file prevents errors such as:
// TS7031: Binding element 'IDL' implicitly has an 'any' type.
> feat: clean factory.did.js

- src/commands/auth.ts
- src/services/login.services.ts
I really thought this display was already implemented. Never too late.
> feat: display the principal used by the terminal for login

- src/services/controllers.services.ts
> feat: review reuse controller instruction

- package-lock.json
- package.json
- src/services/build.services.ts
Required for getrandom v0.3.0 breaking change.
> feat: pass --cfg getrandom_backend="custom" as env for juno dev build

- package-lock.json
- package.json
Embed https://github.com/junobuild/juno-js/pull/257
> feat: windows support for spawn and execute sub-commands

- src/commands/init.ts
> feat: use package manager in intellisense tips

- src/commands/init.ts
> feat: add out to the proposed list of source option

- src/commands/config.ts
> feat: print success or errors of config cmd

- src/utils/auth.utils.ts
> feat: pass profile with login for read-only display in the UI

- eslint.config.mjs
- src/configs/cli.state.config.ts
- src/services/config/config.services.ts
- src/types/cli.state.ts
> feat: config datastore and storage collections

- src/services/config/config.services.ts
Resolve the issue we discovered in today's Juno Live
https://www.youtube.com/watch?v=VPbjZKirKfk
> fix: compare empty list of collections

- src/services/assets/deploy/deploy.assert.services.ts
Relates to https://github.com/junobuild/juno/issues/1813
> feat: in headless mode exit on error if heap memory over limit

- src/api/actor.api.ts
- src/utils/config.utils.ts
> feat: check if cli config exists before trying to get token

- package-lock.json
- package.json
Include https://github.com/junobuild/juno-js/releases/tag/v0.0.180
> feat: bump cli-tools to fix sha comparison in replace mode

- src/services/run.services.ts
Just in case some day we have some issue because of Zod. See https://github.com/junobuild/juno-js/pull/591
> feat: use provided run function instead of the one asserted

- package-lock.json
- package.json
- src/services/emulator/_runner.services.ts
See https://github.com/junobuild/juno-docker/pull/195
> Revert "feat: support for enabling or disabled network services of the emulator (#375)"

- src/commands/auth.ts
- src/services/modules/snapshot/_snapshot.loader.services.ts
- src/services/modules/snapshot/snapshot.services.ts
- src/utils/prompt.utils.ts
It's handy for running the tests but, also for those who want to setup their own E2E in CIs
> feat: snapshot and login emulator no confirm if headless and dev mode

- package-lock.json
- package.json
- src/services/emulator/_runner.services.ts
Relates to https://github.com/junobuild/juno-docker/pull/199 and https://github.com/junobuild/juno-js/pull/600
> feat: support for emulator ports timeout
