- src/commands/help.ts
- src/commands/upgrade.ts
- src/commands/version.ts
- `juno version` = checks version only. "Your satellite v.... is up-to-date." or "Your satelitte v... is behind latest v...."
- `juno upgrade -m ...` = upgrade mission control
- `juno upgrade` = upgrade satellite, no changes here
In addition, add a check to `juno upgrade` to prevent cross semver upgrade (v0.0.2 -> v0.0.4 should first go to v0.0.3)
> feat: upgrade & version

- src/services/login.services.ts
According [security advisory](https://github.com/advisories/GHSA-c9vv-fhgv-cjc3) it's safer for the future, once agent-js patched, to use generate without arguments and not the workaround.
> feat: redo generate without arguments

- src/commands/deploy.ts
- src/constants/deploy.constants.ts
- src/services/deploy.services.ts
> feat: listAssets for deploy with pagination

- src/services/clear.services.ts
The spinner blocks the interaction so the dev cannot enter the secret to read the config
> fix: clear request pwd before spinner

- src/services/clear.services.ts
`juno clear -f /path/to/file` was hanging forever because requesting the pwd to decode the config was requested while ora, the spinner for progression, was running.
> fix: handing clear single file

- src/services/build.services.ts
We need to add `--keep-name-section` to `ic-wasm` if we want to enjoy the upcoming "Canister Backtraces" feature
Source: https://forum.dfinity.org/t/canister-backtraces/35298/9?u=peterparker
> feat: ic-wasm --keep-name-section

- package-lock.json
- package.json
- src/help/upgrade.help.ts
- src/services/upgrade/upgrade.mission-control.services.ts
- src/services/upgrade/upgrade.orbiter.services.ts
- src/services/upgrade/upgrade.satellite.services.ts
- src/services/upgrade/upgrade.services.ts
I mixed both topic, I know not good. I had to debug why install chunked code does not work on mainnet. Still unclear therefore the option was disable so to move forward anyway I merge using a next version.
> feat: handle alredy install wasm code error msg & preClearChunks option

- src/api/actor.api.ts
- src/api/agent.api.ts
The agent is doing all kinds of stuffs on create therefore it's probably best to cache it when we use it.
Note that this improvement leverage another improvement in the admin library which allow to pass a specific agent.
> feat: cache agent

- src/help/upgrade.help.ts
- src/services/upgrade/upgrade.mission-control.services.ts
- src/services/upgrade/upgrade.orbiter.services.ts
- src/services/upgrade/upgrade.satellite.services.ts
- src/services/upgrade/upgrade.services.ts
- src/types/upgrade.ts
- src/utils/process.utils.ts
It's a breaking change but, in the meantime we got now `--headless` which can replace `--nocheck` since that was the idea behind the check.
> feat: remove option --nocheck

- package-lock.json
- package.json
- src/commands/deploy.ts
- src/services/build.services.ts
- src/services/clear.services.ts
- src/services/deploy.services.ts
`core-peer` as been deprecated because `core` now inherits agent-js as peer dependencies.
> feat: replace core-peer by core

- .gitignore
> chore: ignore eject template declarations and did extension

- src/commands/init.ts
- src/configs/juno.config.ts
- src/help/init.help.ts
- src/types/config.ts
A new option for `juno init` which just generates the config with a placeholder. Useful when following the GitHub Actions tutorial.
> feat: juno init --minimal

- src/configs/cli.config.ts
- src/stores/settings.store.ts
When a new user install the CLI, they might just use `juno --version` or just use it to start the local development environment `juno dev start`. In that case, it does not make sense to ask to encode the config since those commands do not require one.
> feat: init settings when required and not globally

- src/constants/dev.constants.ts
As reported today on [Discord](https://discord.com/channels/1076791076544847982/1344599110660915271/1344908738393542699), we added `--keep-name-section` to support canister backtraces but, this requires at least `ic-wasm@0.8.5`  but, the CLI was still checking for a lower version.
```
Error: error: unexpected argument '--keep-name-section' found
```
> fix: minimal version of ic-wasm is v0.8.5

- src/types/pm.ts
- src/utils/pm.utils.ts
Bun is not a package manaer. Let's review this later in #201, meanwhile let's not detect it as it would for example generate a `predeploy [bun build]` command which is actually invalid.
> feat: remove bun detection

- src/services/build/build.javascript.ts
- src/services/build/build.rust.services.ts
- src/services/build/build.services.ts
- src/types/build.ts
Useful to extend build with typesafety if we add more options.
> feat: introduce build args type and mapper

- package-lock.json
- package.json
- src/help/dev.build.help.ts
- src/help/help.ts
- src/services/build/build.services.ts
- src/types/build.ts
Provide an option to support live reloading automatically when building serverless functions.
> feat: juno dev build --watch

- src/constants/help.constants.ts
- src/help/clear.help.ts
- src/help/config.help.ts
- src/help/deploy.help.ts
- src/help/dev.help.ts
- src/help/help.ts
- src/help/init.help.ts
- src/help/login.help.ts
- src/help/logout.help.ts
- src/help/open.help.ts
- src/help/snapshot.help.ts
- src/help/start.help.ts
- src/help/stop.help.ts
- src/help/upgrade.help.ts
- src/help/use.help.ts
- src/help/version.help.ts
- src/help/whoami.help.ts
As a result running e.g. `juno config --help` printed undefined instead of the juno title.
> fix: recursive imports by constants

- src/index.ts
The `juno config --mode staging` was not interpreting the mode because, even though using the mode is implemented, the top level dispatcher of command did not pass the arguments 🤦‍♂️.
> fix: config command does not interpret mode

- package-lock.json
- package.json
- src/constants/dev.constants.ts
- src/services/build/build.javascript.ts
It's annoying and not synchrone to have to use a package.json to pass information from the client to the docker container so better let pass the info through the script. It's tiny.
> feat: pass metadata in mjs

- src/services/build/build.rust.services.ts
The custom normalize version can be replaced with the semver `minVersion`
> feat: replace custom code with minVersion

- src/services/start/docker.services.ts
Docker reference juno config, juno config needs to know which docker image...
> fix: juno dev start detect config

- package-lock.json
- package.json
- src/services/deploy.services.ts
We go back to before v0.3.0 where we used custom memory endpoints for the CLI. We need this to query the informaiton with controllers READ+WRITE in GH Actions.
> fix: revert getting memory with the IC and use custom memory_size

- src/constants/deploy.constants.ts
- src/services/deploy.services.ts
We go back to before v0.3.0 where we used custom memory endpoints for the CLI. We need this to query the informaiton with controllers READ+WRITE in GH Actions.
> fix: revert memory check guard removal

- src/services/modules/upgrade/upgrade-assert.services.ts
- src/utils/wasm.utils.ts
A leftover of the introduction of Juno package. On `juno upgrade` which should assert stock and extended using the new metadata format.
> fix: read build type with juno package

- src/services/modules/upgrade/upgrade-assert.services.ts
- src/services/modules/upgrade/upgrade.services.ts
When upgrading in headless mode, even though we do not want to prompt the dev in this context, we still want to prevent serverless functions to being overwritten. Therefore we run the assertion and throw an error instead. Such an upgrade should be performed manually if really required.
> feat: run assert in headless

- src/constants/dev.constants.ts
- src/services/functions/build/build.rust.services.ts
- src/services/functions/build/build.services.ts
- src/services/functions/build/touch.services.ts
Relates to https://github.com/junobuild/juno-docker/pull/156
> feat: workaround for Podman on macOS

- src/commands/deploy.ts
- src/help/deploy.help.ts
- src/services/config/config.services.ts
- src/services/deploy.services.ts
> feat: juno deploy --config

- src/services/links.services.ts
> feat: print default links in headless

- src/cli/env.loader.ts
- src/commands/whoami.ts
- src/types/cli.env.ts
> feat: add --profile to env and displays it in whoami

- package-lock.json
- package.json
The new breaking change `ready_for_migration` should be available on mainnet but, not necessarly in the tooling. Therefore to avoid issue we downgrade the deps `@dfinity/ic-management` as the did files were updated in 7.0.1
Example of issue: https://github.com/junobuild/juno/actions/runs/17732129974/job/50385566632?pr=1940
> build: downgrade ic-mgmt to avoid issue with if field ready_for_migration is not available

- templates/eject/rust/src/satellite/satellite.did
As released in [v0.0.57](https://github.com/junobuild/juno/releases/tag/v0.0.57)
> feat: update satellite.did template for v0.1.4
